#!/usr/bin/env python3
"""Write src/voMeta.ts — per-scene voiceover file + scene duration in frames.

Two modes:
  estimate (default): derive durations from narration.json word counts.
  --from-audio:       measure the actual public/vo/voNN.wav clips.
Scene duration = LEAD + voiceover + TAIL (padding so the visual breathes).
"""
import json, os, sys, wave, contextlib, math

FPS = 30
LEAD = 1.0          # seconds the scene holds before the voice starts
TAIL = 1.5          # seconds the scene holds after the voice ends
WPM = 150.0

def vo_seconds_estimate(text):
    return len(text.split()) / WPM * 60.0

def vo_seconds_audio(scene):
    p = f"public/vo/vo{scene:02d}.wav"
    with contextlib.closing(wave.open(p, "r")) as w:
        return w.getnframes() / float(w.getframerate())

def main():
    use_audio = "--from-audio" in sys.argv
    scenes = json.load(open("scripts/narration.json"))
    rows = []
    for s in scenes:
        vo = vo_seconds_audio(s["scene"]) if use_audio else vo_seconds_estimate(s["text"])
        frames = int(round((LEAD + vo + TAIL) * FPS))
        rows.append((s["scene"], frames))
    with open("src/voMeta.ts", "w") as f:
        f.write("// Auto-generated by scripts/write_vometa.py — do not hand-edit.\n")
        f.write(f"export const VO_LEAD_FRAMES = {int(round(LEAD*FPS))};\n")
        f.write("export const VO: { file: string; d: number }[] = [\n")
        for scn, frames in rows:
            f.write(f'  {{ file: "vo/vo{scn:02d}.wav", d: {frames} }},\n')
        f.write("];\n")
    total = sum(r[1] for r in rows)
    print(f"wrote src/voMeta.ts  ({'audio' if use_audio else 'estimate'})  total {total} frames = {total/FPS:.0f}s")

if __name__ == "__main__":
    main()
